// ─────────────────────────────────────────────────────────────────
// generate.cjs — layout engine for content.md
//
// This file OWNS THE LAYOUT (fonts, sizes, ATS-safe structure, margins).
// It DOES NOT OWN THE CONTENT. All resume text lives in content.md.
// Do not edit this file to change what's ON your resume; edit content.md.
//
// Parser is intentionally strict about the schema documented in
// content.md's header comment. Malformed input throws with a clear
// error at the line that failed.
// ─────────────────────────────────────────────────────────────────
const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, AlignmentType, LevelFormat,
  ExternalHyperlink, TabStopType, TabStopPosition, BorderStyle,
} = require("docx");

// ── layout constants ─────────────────────────────────────────────
const FONT = "Calibri";
const BODY = 20;      // 10pt (half-points)
const SMALL = 19;     // 9.5pt
const NAME = 31;      // 16.5pt
const HEAD = 21;      // 10.5pt
const ACCENT = "1F4E79";

// ── layout helpers (unchanged from the previous generator) ───────
const sectionHeading = (text) =>
  new Paragraph({
    spacing: { before: 70, after: 30 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: ACCENT, space: 2 } },
    children: [new TextRun({ text, bold: true, size: HEAD, color: ACCENT, font: FONT, allCaps: true })],
  });

const roleLine = (title, orgAndLocation, date) =>
  new Paragraph({
    spacing: { before: 40, after: 12 },
    tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
    children: [
      new TextRun({ text: title, bold: true, size: BODY, font: FONT }),
      new TextRun({ text: ` — ${orgAndLocation}`, size: BODY, font: FONT }),
      new TextRun({ text: `\t${date}`, bold: true, size: SMALL, font: FONT }),
    ],
  });

const bulletParagraph = (runs) =>
  new Paragraph({
    numbering: { reference: "b", level: 0 },
    spacing: { after: 10 },
    children: runs.map((r) => new TextRun({ font: FONT, size: BODY, ...r })),
  });

const link = (text, url) =>
  new ExternalHyperlink({
    children: [new TextRun({ text, style: "Hyperlink", size: SMALL, font: FONT })],
    link: url,
  });

const skillsLine = (label, items) =>
  new Paragraph({
    spacing: { after: 12 },
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: BODY, font: FONT }),
      new TextRun({ text: items, size: BODY, font: FONT }),
    ],
  });

const summaryParagraph = (text) =>
  new Paragraph({
    spacing: { after: 20 },
    children: [new TextRun({ font: FONT, size: BODY, text })],
  });

const educationDetail = (text) =>
  new Paragraph({
    spacing: { after: 0 },
    indent: { left: 260 },
    children: [new TextRun({ font: FONT, size: SMALL, text })],
  });

// ── Markdown parser ──────────────────────────────────────────────
// Small, purpose-built. Handles exactly the shapes documented in
// content.md's header. No external Markdown lib (would over-parse:
// e.g. render our `.docx` filename as inline code).

/** Split inline `**bold**` runs. Preserves order. */
function parseInlineBold(text) {
  const runs = [];
  const re = /\*\*([^*]+)\*\*/g;
  let cursor = 0;
  let m;
  while ((m = re.exec(text)) !== null) {
    if (m.index > cursor) {
      runs.push({ text: text.slice(cursor, m.index) });
    }
    runs.push({ text: m[1], bold: true });
    cursor = re.lastIndex;
  }
  if (cursor < text.length) runs.push({ text: text.slice(cursor) });
  return runs.length ? runs : [{ text }];
}

/**
 * Split a contact-line by " | " and turn each cell into a TextRun /
 * ExternalHyperlink. Supports `[text](url)` for linked cells.
 */
function parseContactCells(line) {
  const separator = new TextRun({ text: "  |  ", size: SMALL, font: FONT });
  const children = [];
  const cells = line.split(/\s*\|\s*/);
  cells.forEach((cell, i) => {
    if (i > 0) children.push(separator);
    const linkMatch = cell.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
    if (linkMatch) {
      children.push(link(linkMatch[1], linkMatch[2]));
    } else {
      children.push(new TextRun({ text: cell, size: SMALL, font: FONT }));
    }
  });
  return children;
}

/**
 * Parse `content.md` into a list of docx paragraphs.
 * Throws with the offending line number if the schema is violated.
 */
function parseResume(md) {
  // Strip HTML comments (may span multiple lines). This is how the
  // schema doc-block at the top of content.md is hidden from the
  // parser. Match non-greedily; `s` flag lets `.` match newlines.
  const withoutComments = md.replace(/<!--[\s\S]*?-->/g, "");

  const rawLines = withoutComments.split(/\r?\n/);
  const lines = rawLines
    .map((l, i) => ({ text: l, num: i + 1 }))
    .filter(({ text }) => text.trim() !== "");

  const out = [];
  let currentSection = null;   // "Summary" | "Technical Skills" | ...
  let i = 0;

  // Header: expect `# NAME` then a contact line
  if (i >= lines.length || !lines[i].text.match(/^# /)) {
    throw new Error(`content.md line ${lines[i]?.num || 1}: expected a '# NAME' header at the top`);
  }
  const name = lines[i].text.replace(/^# /, "").trim();
  i++;

  // Optional: a run of comment lines (starting with #) that live between
  // the name and the contact line, or the very first '# NAME' line was
  // preceded by an entire comment block already filtered out above.
  // The contact line is the first line that's not a heading.
  if (i >= lines.length) {
    throw new Error(`content.md: name found but no contact line follows`);
  }
  const contactLine = lines[i].text.trim();
  i++;

  out.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 20 },
    children: [new TextRun({ text: name, bold: true, size: NAME, font: FONT, color: ACCENT })],
  }));
  out.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 40 },
    children: parseContactCells(contactLine),
  }));

  while (i < lines.length) {
    const { text, num } = lines[i];

    if (text.startsWith("## ")) {
      currentSection = text.slice(3).trim();
      out.push(sectionHeading(currentSection));
      i++;
      continue;
    }

    if (text.startsWith("### ")) {
      // Role line: "### Title — Org · Date"
      const roleText = text.slice(4).trim();
      // Split on the last " · " (date is always after a middle dot)
      const dotIdx = roleText.lastIndexOf(" · ");
      if (dotIdx < 0) {
        throw new Error(`content.md line ${num}: role line missing ' · <date>' — got: ${roleText}`);
      }
      const before = roleText.slice(0, dotIdx);
      const date = roleText.slice(dotIdx + 3).trim();
      // Split "Title — Org" on the first " — "
      const dashIdx = before.indexOf(" — ");
      if (dashIdx < 0) {
        throw new Error(`content.md line ${num}: role line missing ' — <org>' — got: ${before}`);
      }
      const title = before.slice(0, dashIdx).trim();
      const org = before.slice(dashIdx + 3).trim();
      out.push(roleLine(title, org, date));
      i++;
      continue;
    }

    if (text.startsWith("- ")) {
      const body = text.slice(2).trim();

      // Skills section: bullets are "Label: items"
      if (currentSection === "Technical Skills") {
        const colon = body.indexOf(":");
        if (colon < 0) {
          throw new Error(`content.md line ${num}: skills line missing 'Label:' — got: ${body}`);
        }
        const label = body.slice(0, colon).trim();
        const items = body.slice(colon + 1).trim();
        out.push(skillsLine(label, items));
        i++;
        continue;
      }

      // Education section: bullets are single-paragraph indented notes
      if (currentSection === "Education") {
        out.push(educationDetail(body));
        i++;
        continue;
      }

      // Everything else: real bulleted list item (with **bold** runs)
      out.push(bulletParagraph(parseInlineBold(body)));
      i++;
      continue;
    }

    // Plain paragraph — only expected under Summary
    if (currentSection === "Summary") {
      out.push(summaryParagraph(text.trim()));
      i++;
      continue;
    }

    throw new Error(`content.md line ${num}: unrecognized line under section '${currentSection}': ${text}`);
  }

  return out;
}

// ── main ─────────────────────────────────────────────────────────
const markdown = fs.readFileSync("content.md", "utf8");
const children = parseResume(markdown);

const doc = new Document({
  styles: { default: { document: { run: { font: FONT, size: BODY } } } },
  numbering: {
    config: [{
      reference: "b",
      levels: [{
        level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
        style: { paragraph: { indent: { left: 260, hanging: 160 } } },
      }],
    }],
  },
  sections: [{
    properties: {
      page: {
        size: { width: 12240, height: 15840 },
        margin: { top: 560, right: 700, bottom: 420, left: 700 },
      },
    },
    children,
  }],
});

Packer.toBuffer(doc).then((buf) => {
  fs.writeFileSync("Uday_Ojha_Resume.docx", buf);
  console.log("written", buf.length, "bytes");
});
